project:
  type: website

website:
  title: "Oscar Herrera Molinares"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/
format:
  html:
    theme: Litera
    css: styles.css

editor: visual

